services:
    _defaults:
        autowire: true
        autoconfigure: true

    Adeliom\EasyPageBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]

    easy_page.route_loader:
        class: Adeliom\EasyPageBundle\Routing\PageLoader
        arguments:
            - '%easy_page.page_controller%'
            - '%easy_page.page_class%'
            - '@easy_page.repository'
            - '%easy_page.trailing_slash%'
            - '%kernel.environment%'
        tags: [ routing.loader ]

    easy_page.repository:
        class: '%easy_page.page_repository%'
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '%easy_page.page_class%'
        calls:
            - [ 'setConfig', [ '%easy_page.cache%' ] ]
        tags: [ doctrine.repository_service ]

    Adeliom\EasyPageBundle\EventListener\LayoutsListener:
        arguments:
            - '%easy_page.layouts%'
            - '@twig'
            - '@easy_page.repository'
        tags:
            - kernel.event_subscriber

    Adeliom\EasyPageBundle\EventListener\DoctrineMappingListener:
        arguments:
            - '%easy_page.page_class%'
        tags:
            - doctrine.event_subscriber

    easy_page.sitemap.page_subscriber:
        class: Adeliom\EasyPageBundle\EventListener\SitemapSubscriber
        arguments:
            - "@router"
            - "@easy_page.repository"
            - "%easy_page.sitemap%"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    Adeliom\EasyPageBundle\DataCollector\PageCollector:
        arguments:
            - "@parameter_bag"
        tags:
            - name: data_collector
              template: '@EasyPage/profiler/collector.html.twig'
              id: Adeliom\EasyPageBundle\DataCollector\PageCollector
